<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('municipios')->insert(['municipio' => 'Ayo Ayo','provincia_id' => 1,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Calamarca','provincia_id' => 1,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Collana','provincia_id' => 1,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Colquencha','provincia_id' => 1,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Patacamaya','provincia_id' => 1,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sica Sica','provincia_id' => 1,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Umala','provincia_id' => 1,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Charazani','provincia_id' => 2,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Curva','provincia_id' => 2,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Escoma','provincia_id' => 3,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Humanata','provincia_id' => 3,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Mocomoco','provincia_id' => 3,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Acosta','provincia_id' => 3,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Carabuco','provincia_id' => 3,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Alto Beni','provincia_id' => 4,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Caranavi','provincia_id' => 4,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Apolo','provincia_id' => 5,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pelechuco','provincia_id' => 5,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Catacora','provincia_id' => 6,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santiago de Machaca','provincia_id' => 6,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chacarilla','provincia_id' => 7,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Papel Pampa','provincia_id' => 7,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Pedro de Curahuara','provincia_id' => 7,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Desaguadero','provincia_id' => 8,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Guaqui','provincia_id' => 8,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Jesús de Machaca','provincia_id' => 8,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Andrés de Machaca','provincia_id' => 8,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Taraco','provincia_id' => 8,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tiahuanaco','provincia_id' => 8,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Viacha','provincia_id' => 8,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cajuata','provincia_id' => 9,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Colquiri','provincia_id' => 9,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ichoca','provincia_id' => 9,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Inquisivi','provincia_id' => 9,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Licoma Pampa','provincia_id' => 9,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Quime','provincia_id' => 9,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ixiamas','provincia_id' => 10,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Buenaventura','provincia_id' => 10,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Combaya','provincia_id' => 11,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Guanay','provincia_id' => 11,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Mapiri','provincia_id' => 11,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Quiabaya','provincia_id' => 11,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sorata','provincia_id' => 11,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tacacoma','provincia_id' => 11,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Teoponte','provincia_id' => 11,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tipuani','provincia_id' => 11,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cairoma','provincia_id' => 12,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Luribay','provincia_id' => 12,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Malla','provincia_id' => 12,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sapahaqui','provincia_id' => 12,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Yaco','provincia_id' => 12,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Batallas','provincia_id' => 13,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Laja','provincia_id' => 13,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pucarani','provincia_id' => 13,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Pérez','provincia_id' => 13,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Copacabana','provincia_id' => 14,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Pedro de Tiquina','provincia_id' => 14,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tito Yupanqui','provincia_id' => 14,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Aucapata','provincia_id' => 15,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ayata','provincia_id' => 15,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chuma','provincia_id' => 15,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Achocalla','provincia_id' => 16,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'El Alto','provincia_id' => 16,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'La Paz','provincia_id' => 16,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Mecapaca','provincia_id' => 16,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Palca','provincia_id' => 16,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Coripata','provincia_id' => 17,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Coroico','provincia_id' => 17,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Achacachi','provincia_id' => 18,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ancoraimes','provincia_id' => 18,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chua Cocani','provincia_id' => 18,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Huarina','provincia_id' => 18,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Huatajata','provincia_id' => 18,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santiago de Huata','provincia_id' => 18,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Calacoto','provincia_id' => 19,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Callapa','provincia_id' => 19,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Caquiaviri','provincia_id' => 19,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Charaña','provincia_id' => 19,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Comanche','provincia_id' => 19,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Coro Coro','provincia_id' => 19,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Nazacara de Pacajes','provincia_id' => 19,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Waldo Ballivián','provincia_id' => 19,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chulumani','provincia_id' => 20,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Irupana','provincia_id' => 20,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'La Asunta','provincia_id' => 20,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Palos Blancos','provincia_id' => 20,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Yanacachi','provincia_id' => 20,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Challapata','provincia_id' => 21,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Quillacas','provincia_id' => 21,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Choquecota','provincia_id' => 22,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Corque','provincia_id' => 22,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Caracollo','provincia_id' => 23,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'El Choro','provincia_id' => 23,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Oruro','provincia_id' => 23,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Paria','provincia_id' => 23,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Huanuni','provincia_id' => 24,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Machacamarca','provincia_id' => 24,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pampa Aullagas','provincia_id' => 25,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Salinas de Garci Mendoza','provincia_id' => 25,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cruz de Machacamarca','provincia_id' => 26,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Escara','provincia_id' => 26,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Esmeralda','provincia_id' => 26,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Huachacalla','provincia_id' => 26,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Yunguyo de Litoral','provincia_id' => 26,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Carangas','provincia_id' => 27,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'La Rivera','provincia_id' => 27,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Todos Santos','provincia_id' => 27,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Huayllamarca','provincia_id' => 28,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Antequera','provincia_id' => 29,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pazña','provincia_id' => 29,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Poopó','provincia_id' => 29,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chipaya','provincia_id' => 30,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Coipasa','provincia_id' => 30,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sabaya','provincia_id' => 30,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Curahuara de Carangas','provincia_id' => 31,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Turco','provincia_id' => 31,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Totora','provincia_id' => 32,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Toledo','provincia_id' => 33,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santiago de Huari','provincia_id' => 34,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Belén de Andamarca','provincia_id' => 35,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santiago de Andamarca','provincia_id' => 35,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Eucaliptus','provincia_id' => 36,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Caripuyo','provincia_id' => 37,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sacaca','provincia_id' => 37,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Pedro de Buena Vista','provincia_id' => 38,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Toro Toro','provincia_id' => 38,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Colquechaca','provincia_id' => 39,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ocurí','provincia_id' => 39,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pocoata','provincia_id' => 39,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ravelo','provincia_id' => 39,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Pedro de Macha','provincia_id' => 39,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Betanzos','provincia_id' => 40,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chaquí','provincia_id' => 40,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tacobamba','provincia_id' => 40,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Llica','provincia_id' => 41,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tahua','provincia_id' => 41,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Agustín','provincia_id' => 42,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Acasio','provincia_id' => 43,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Arampampa','provincia_id' => 43,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Caiza D','provincia_id' => 44,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ckochas','provincia_id' => 44,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puna','provincia_id' => 44,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villazón','provincia_id' => 45,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cotagaita','provincia_id' => 46,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Vitichi','provincia_id' => 46,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Colcha K','provincia_id' => 47,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Pedro de Quemes','provincia_id' => 47,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Porco','provincia_id' => 48,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tomave','provincia_id' => 48,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Uyuni','provincia_id' => 48,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chayanta','provincia_id' => 49,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chuquihuta','provincia_id' => 49,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Llallagua','provincia_id' => 49,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Uncía','provincia_id' => 49,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Atocha','provincia_id' => 50,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tupiza','provincia_id' => 50,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Mojinete','provincia_id' => 51,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Antonio de Esmoruco','provincia_id' => 51,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Pablo de Lípez','provincia_id' => 51,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Potosí','provincia_id' => 52,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tinguipaya','provincia_id' => 52,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Urmiri','provincia_id' => 52,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Yocalla','provincia_id' => 52,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Arani','provincia_id' => 53,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Vacas','provincia_id' => 53,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Arque','provincia_id' => 54,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tacopaya','provincia_id' => 54,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cocapata','provincia_id' => 55,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Independencia','provincia_id' => 55,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Morochata','provincia_id' => 55,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Bolívar','provincia_id' => 56,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Aiquile','provincia_id' => 57,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Omereque','provincia_id' => 57,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pasorapa','provincia_id' => 57,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Capinota','provincia_id' => 58,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santiváñez','provincia_id' => 58,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sicaya','provincia_id' => 58,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Chimoré','provincia_id' => 59,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Entre Ríos','provincia_id' => 59,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pocona','provincia_id' => 59,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pojo','provincia_id' => 59,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Villarroel','provincia_id' => 59,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Totora','provincia_id' => 59,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cochabamba','provincia_id' => 60,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Colomi','provincia_id' => 61,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sacaba','provincia_id' => 61,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Tunari','provincia_id' => 61,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Anzaldo','provincia_id' => 62,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Arbieto','provincia_id' => 62,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sacabamba','provincia_id' => 62,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tarata','provincia_id' => 62,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cliza','provincia_id' => 63,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Toco','provincia_id' => 63,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tolata','provincia_id' => 63,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Alalay','provincia_id' => 64,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Mizque','provincia_id' => 64,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Vila Vila','provincia_id' => 64,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cuchumuela','provincia_id' => 65,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Punata','provincia_id' => 65,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Benito','provincia_id' => 65,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tacachi','provincia_id' => 65,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Rivero','provincia_id' => 65,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Colcapirhua','provincia_id' => 66,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Quillacollo','provincia_id' => 66,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sipe Sipe','provincia_id' => 66,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tiquipaya','provincia_id' => 66,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Vinto','provincia_id' => 66,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tapacarí','provincia_id' => 67,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Shinahota','provincia_id' => 68,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tiraque','provincia_id' => 68,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Azurduy','provincia_id' => 69,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tarvita','provincia_id' => 69,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Serrano','provincia_id' => 70,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Huacareta','provincia_id' => 71,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Monteagudo','provincia_id' => 71,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Huacaya','provincia_id' => 72,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Macharetí','provincia_id' => 72,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Vaca Guzmán (Muyupampa)','provincia_id' => 72,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Camargo','provincia_id' => 73,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Incahuasi','provincia_id' => 73,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Lucas','provincia_id' => 73,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Charcas','provincia_id' => 73,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Poroma','provincia_id' => 74,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sucre','provincia_id' => 74,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Yotala','provincia_id' => 74,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Culpina','provincia_id' => 75,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Las Carreras','provincia_id' => 75,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Abecia','provincia_id' => 75,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'El Villar','provincia_id' => 76,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Padilla','provincia_id' => 76,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sopachuy','provincia_id' => 76,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tomina','provincia_id' => 76,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Alcalá','provincia_id' => 76,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tarabuco','provincia_id' => 77,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Yamparáez','provincia_id' => 77,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Icla','provincia_id' => 78,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Presto','provincia_id' => 78,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Mojocoya','provincia_id' => 78,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Zudáñez','provincia_id' => 78,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Bermejo','provincia_id' => 79,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Padcaya','provincia_id' => 79,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Tarija','provincia_id' => 80,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Caraparí','provincia_id' => 81,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Montes','provincia_id' => 81,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Yacuiba','provincia_id' => 81,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Uriondo','provincia_id' => 82,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Yunchará','provincia_id' => 82,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'El Puente','provincia_id' => 83,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Lorenzo','provincia_id' => 83,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Entre Ríos','provincia_id' => 84,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ingavi','provincia_id' => 85,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santa Rosa del Abuná','provincia_id' => 85,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Nueva Esperanza','provincia_id' => 86,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santos Mercado','provincia_id' => 86,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Nueva','provincia_id' => 86,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Gonzalo Moreno','provincia_id' => 87,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Lorenzo','provincia_id' => 87,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Sena','provincia_id' => 87,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Filadelfia','provincia_id' => 88,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Rico','provincia_id' => 88,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Pedro','provincia_id' => 88,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Bella Flor','provincia_id' => 89,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Bolpebra','provincia_id' => 89,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cobija','provincia_id' => 89,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Porvenir','provincia_id' => 89,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Javier','provincia_id' => 90,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Trinidad','provincia_id' => 90,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Reyes','provincia_id' => 91,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Rurrenabaque','provincia_id' => 91,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Borja','provincia_id' => 91,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santa Rosa','provincia_id' => 91,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Baures','provincia_id' => 92,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Huacaraje','provincia_id' => 92,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Magdalena','provincia_id' => 92,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Siles','provincia_id' => 93,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Joaquín','provincia_id' => 93,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Ramón','provincia_id' => 93,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Loreto','provincia_id' => 94,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Andrés','provincia_id' => 94,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Ignacio de Moxos','provincia_id' => 95,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Guayaramerín','provincia_id' => 96,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Riberalta','provincia_id' => 96,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Exaltación','provincia_id' => 97,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santa Ana del Yacuma','provincia_id' => 97,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cotoca','provincia_id' => 98,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'El Torno','provincia_id' => 98,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'La Guardia','provincia_id' => 98,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Porongo','provincia_id' => 98,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santa Cruz de la Sierra','provincia_id' => 98,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Matías','provincia_id' => 99,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Comarapa','provincia_id' => 100,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Saipina','provincia_id' => 100,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pailón','provincia_id' => 101,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Roboré','provincia_id' => 101,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San José de Chiquitos','provincia_id' => 101,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Boyuibe','provincia_id' => 102,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cabezas','provincia_id' => 102,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Camiri','provincia_id' => 102,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Charagua','provincia_id' => 102,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cuevo','provincia_id' => 102,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Gutiérrez (Kereimba Iyambae)','provincia_id' => 102,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Lagunillas','provincia_id' => 102,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Mairana','provincia_id' => 103,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pampagrande','provincia_id' => 103,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Quirusillas','provincia_id' => 103,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Samaipata','provincia_id' => 103,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'El Carmen Rivero Tórrez','provincia_id' => 104,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Quijarro','provincia_id' => 104,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Puerto Suárez','provincia_id' => 104,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Ascensión de Guarayos','provincia_id' => 105,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'El Puente','provincia_id' => 105,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Urubichá','provincia_id' => 105,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Buena Vista','provincia_id' => 106,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Carlos','provincia_id' => 106,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Juan de Yapacaní','provincia_id' => 106,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Villa Yapacaní','provincia_id' => 106,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Concepción','provincia_id' => 107,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Cuatro Cañadas','provincia_id' => 107,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Antonio de Lomerío','provincia_id' => 107,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Javier','provincia_id' => 107,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Julián','provincia_id' => 107,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Ramón','provincia_id' => 107,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Fernández Alonso','provincia_id' => 108,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'General Saavedra','provincia_id' => 108,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Mineros','provincia_id' => 108,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Montero','provincia_id' => 108,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Pedro','provincia_id' => 108,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Colpa Bélgica','provincia_id' => 109,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Portachuelo','provincia_id' => 109,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Santa Rosa del Sara','provincia_id' => 109,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'El Trigal','provincia_id' => 110,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Moro Moro','provincia_id' => 110,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Postrervalle','provincia_id' => 110,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Pucará','provincia_id' => 110,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Vallegrande','provincia_id' => 110,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Ignacio de Velasco','provincia_id' => 111,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Miguel de Velasco','provincia_id' => 111,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'San Rafael de Velasco','provincia_id' => 111,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Okinawa Uno','provincia_id' => 112,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);
        DB::table('municipios')->insert(['municipio' => 'Warnes','provincia_id' => 112,'created_at'=>\Carbon\Carbon::now(),'updated_at'=>\Carbon\Carbon::now()]);

    }
}
